### ISSUE TITLE
Testing array of longs

### ISSUE THREAD

**Issue by michaelmcneilnet** [johnmwright/Fakes.Contrib#2]
I am trying to test that a method received an array of longs like this:

```
this.stubObj.AssertWasCalled(stub => stub.MyMethod(With.Any<long[]>));
```

This throws the following exception when hitting the above assertion:

> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load TypeSpec from assembly 'DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=a621a9e7e5c32e69'.

**Comment by johnmwright** [comment]
This appears to no longer be an issue. I am unable to reproduce and have added a set of tests which are able to successfully assert against a method that takes arrays of various types. (see: https://github.com/johnmwright/Fakes.Contrib/pull/8)

If you're still having this issue (I know it's been a while since it was filed), please let me know.
